### ISSUE TITLE
Internal error: Should commit log before counting. Please report a bug!

### ISSUE THREAD

**Issue by spelexander** [LastOliveGames/becsy#22] opened 2022-10-12 21:57 UTC
Hi there! First off thanks for such an awesome ECS library. I'm continually surprised by the sophistication and richness of features throughout becsy.

I noticed recently an increasing pattern of: 
> Internal error: Should commit log before counting. Please report a bug!

I unfortunately don't have a whole lot more to share because it's happening on a remote test machine with no apparent effect to operation and I'm unable to reproduce locally, apologies. 

I was wondering if you could share some information about this error, and perhaps provide advice about how to debug the cause?

**Comment by pkaminski** [comment] 2022-10-13 01:39
Hey Alex, thanks for the kind words and sorry about the bug.  For context, log counting is used by the stats subsystem, which is not mission-critical.  I'd still expect the exception to crash the process, though, since it can prevent some other work that follow the calls from completing -- if that's not happening I'd take a look at your exception propagation logic when calling `execute`.

You can work around the issue by using the `perf` build, which excludes the stats subsystem altogether.

To debug this, we'll need more information.  I pushed v0.15.1, with improved error messages that will at least tell us which log this is happening for -- it should cut down the search space a lot.  Could you please rebuild with the new version and let me know when you see the error again?  Thanks!

**Comment by spelexander** [comment] 2022-10-14 22:17
Thanks for the quick response and the context about the stats subsystem!

I've bumped becsy to 0.15.1 and will get back to you asap with any additional information next it happens

**Comment by spelexander** [comment] 2022-10-17 00:41
Okay back with an improved error message:
`Should commit log maxWritesPerFrame before counting. Please report a bug`

Also, I have confirmed it should definitely be running in perf mode when we see this FYI (using `@lastolivegames/becsy/perf`)

**Comment by pkaminski** [comment] 2022-10-17 02:11
Yeah, the perf build couldn't possibly produce that error -- the error message isn't even present in the distro file.

This identifies the write log as the culprit.  A few more questions to eliminate some scenarios:
1. Does this error happen at startup, in operation, or at finalization (if you use `world.terminate`)?
2. Do you use [custom executors](https://lastolivegames.github.io/becsy/guide/architecture/world.html#start-stop), or just call `world.execute`?
3. Is it possible you're discarding / ignoring any exceptions emitted while executing?  (For example, calling async functions without awaiting the promise.)

**Comment by pkaminski** [comment] 2022-10-17 03:32
I also released 0.15.2, which fixes some internal spots where Becsy was failing to properly block on nominally async functions (though their implementation was in fact synchronous).  This could've discarded some exceptions depending on environment and exception capture strategies.  I doubt it's the cause of the issue here but who knows...

**Comment by pkaminski** [comment] 2022-10-17 06:11
I found and fixed one root cause of this error in 0.15.3 (related to auto-clearing of ref fields when an entity is deleted).  Please give it a try and let me know if it works for you.  Thanks!

**Comment by spelexander** [comment] 2022-10-17 22:29
That's awesome, thank you! Bumping to 0.15.3 now.

1. Does this error happen at startup, in operation, or at finalization (if you use world.terminate)?
The error was certainly happening during execute. To be honest I'm not totally sure at what time though. As I mentioned it's running on a remote machine where I don't have a lot of visibility into the problem. So far it's actually yet to cause any problems locally, was just generating noise!

2. Do you use [custom executors](https://lastolivegames.github.io/becsy/guide/architecture/world.html#start-stop), or just call world.execute?
Just world.execute. I was actually unaware of the custom executors features, that's neat.

3. Is it possible you're discarding / ignoring any exceptions emitted while executing? (For example, calling async functions without awaiting the promise.)
Absolutely, after your message I've tried to track down the main places where this could be happening (there's a few of them though).

**Closed** 2022-10-18 04:33 UTC
Labels: bug
